# The URL the site will be built for
base_url = "https://macromogic.xyz"
theme = "DeepThought"
title = "Macromogic"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", feed = true, paginate_by = 10 },
]

slugify.anchors = "on"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

toc = true

katex.enabled = true
katex.auto_render = true

chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts", name = "Posts" },
  { url = "$BASE_URL/tags", name = "Tags" },
  { url = "$BASE_URL/categories", name = "Categories" },
  { url = "$BASE_URL/pubs", name = "Publications" },
  { url = "$BASE_URL/cv.pdf", name = "CV" },
  { url = "$BASE_URL/friends", name = "Friends" },
 ]},
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "Weijie Huang"

[extra.social]
bilibili = "51291249"
linkedin = "炜杰-黄-94aa11235"
github = "macromogic"
gitlab = "macromogic"
email = "Weijie.Huang@rice.edu"
discord = "macromogic"
google_scholar = "L8T5nBEAAAAJ"
orcid = "0009-0003-6017-0474"